#!/usr/bin/env node
/*
 * Copyright 2026 John Ewart <john@johnewart.net>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Konstruct MCP server — exposes Konstruct's tool implementations over the
 * Model Context Protocol (JSON-RPC 2.0 / stdio transport).
 *
 * Invoked automatically by the Claude CLI when --mcp-config points to a config
 * generated by createKonstruktMcpConfig(). Not intended for direct use.
 *
 * Usage:
 *   bun run src/agent/mcp-server.ts --project /path/to/project [--mode ask]
 *
 * Options:
 *   --project <path>   Project root for tool path resolution (default: cwd)
 *   --mode <mode>      Which Konstruct mode's toolset to expose (default: ask)
 */

import './tools/runners.ts'; // register all tool implementations
import { executeTool } from './tools/executor.ts';
import { getToolsForMode } from './toolDefinitions.ts';
import type { ToolDefinition } from '../shared/llm.ts';
import * as readline from 'node:readline';

// ---------------------------------------------------------------------------
// Arg parsing
// ---------------------------------------------------------------------------

const argv = process.argv.slice(2);
let projectRoot = process.cwd();
let modeId = 'ask';

for (let i = 0; i < argv.length; i++) {
  if (argv[i] === '--project' && argv[i + 1]) projectRoot = argv[++i];
  else if (argv[i] === '--mode' && argv[i + 1]) modeId = argv[++i];
}

// ---------------------------------------------------------------------------
// Tool list for the selected mode (filter out session-only tools)
// ---------------------------------------------------------------------------

const SESSION_TOOLS = new Set(['list_todos', 'add_todo', 'update_todo', 'update_session_title']);

const tools: ToolDefinition[] = getToolsForMode(modeId).filter(
  (t) => !SESSION_TOOLS.has(t.function.name)
);

// Convert Konstruct tool def → MCP inputSchema format
function toMcpTool(t: ToolDefinition) {
  return {
    name: t.function.name,
    description: t.function.description,
    inputSchema: t.function.parameters,
  };
}

const mcpTools = tools.map(toMcpTool);

// ---------------------------------------------------------------------------
// JSON-RPC 2.0 helpers
// ---------------------------------------------------------------------------

type JsonRpcId = string | number | null;

function send(id: JsonRpcId, result: unknown): void {
  process.stdout.write(JSON.stringify({ jsonrpc: '2.0', id, result }) + '\n');
}

function sendError(id: JsonRpcId, code: number, message: string): void {
  process.stdout.write(
    JSON.stringify({ jsonrpc: '2.0', id, error: { code, message } }) + '\n'
  );
}

// ---------------------------------------------------------------------------
// Request dispatcher
// ---------------------------------------------------------------------------

async function handle(req: {
  jsonrpc: string;
  id?: JsonRpcId;
  method: string;
  params?: unknown;
}): Promise<void> {
  const id = req.id ?? null;

  switch (req.method) {
    case 'initialize':
      send(id, {
        protocolVersion: '2024-11-05',
        capabilities: { tools: {} },
        serverInfo: { name: 'konstruct', version: '1.0.0' },
      });
      break;

    case 'notifications/initialized':
      // Notification — no response
      break;

    case 'tools/list':
      send(id, { tools: mcpTools });
      break;

    case 'tools/call': {
      const p = req.params as { name?: string; arguments?: Record<string, unknown> } | undefined;
      if (!p?.name) {
        sendError(id, -32602, 'Missing tool name');
        return;
      }
      try {
        const result = await executeTool(p.name, p.arguments ?? {}, { projectRoot });
        const text = result.error ?? result.result ?? '';
        send(id, {
          content: [{ type: 'text', text }],
          isError: !!result.error,
        });
      } catch (err) {
        send(id, {
          content: [{ type: 'text', text: String(err) }],
          isError: true,
        });
      }
      break;
    }

    default:
      if (req.id != null) {
        sendError(id, -32601, `Method not found: ${req.method}`);
      }
  }
}

// ---------------------------------------------------------------------------
// stdio loop
// ---------------------------------------------------------------------------

const rl = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });

rl.on('line', (line) => {
  const trimmed = line.trim();
  if (!trimmed) return;
  let req: { jsonrpc: string; id?: JsonRpcId; method: string; params?: unknown };
  try {
    req = JSON.parse(trimmed) as typeof req;
  } catch {
    sendError(null, -32700, 'Parse error');
    return;
  }
  handle(req).catch((err) => {
    sendError(req.id ?? null, -32603, String(err));
  });
});

rl.on('close', () => process.exit(0));
